"""PDF generation for Nursing Council reports."""

import io
from datetime import datetime
from typing import Dict, Any, List
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.units import inch

def generate_pdf_report(conversation: Dict[str, Any]) -> bytes:
    """
    Generate a PDF report for a conversation.
    
    Args:
        conversation: The full conversation object containing messages and metadata.
        
    Returns:
        Bytes object containing the PDF data.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=72,
        leftMargin=72,
        topMargin=72,
        bottomMargin=72,
        title=f"Nursing Council Report - {conversation.get('title', 'Unknown')}"
    )

    # Styles
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        spaceAfter=30,
        textColor=colors.HexColor('#2e1065')  # Dark purple
    )
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=18,
        spaceBefore=20,
        spaceAfter=10,
        textColor=colors.HexColor('#4c1d95')
    )
    subheading_style = ParagraphStyle(
        'CustomSubHeading',
        parent=styles['Heading3'],
        fontSize=14,
        spaceBefore=15,
        spaceAfter=5,
        textColor=colors.HexColor('#5b21b6')
    )
    normal_style = styles['Normal']
    normal_style.spaceAfter = 10
    
    # Content elements
    elements = []

    # Title
    elements.append(Paragraph("Nursing Council Report", title_style))
    elements.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#e5e7eb')))
    elements.append(Spacer(1, 20))

    # Metadata
    created_at = conversation.get('created_at', datetime.now().isoformat())
    try:
        date_str = datetime.fromisoformat(created_at).strftime("%B %d, %Y at %H:%M")
    except:
        date_str = created_at

    meta_data = [
        ["Title:", conversation.get('title', 'Untitled Review')],
        ["Date:", date_str],
        ["ID:", conversation.get('id', 'N/A')]
    ]
    t = Table(meta_data, colWidths=[1*inch, 5*inch])
    t.setStyle(TableStyle([
        ('FONTNAME', (0,0), (0,-1), 'Helvetica-Bold'),
        ('TEXTCOLOR', (0,0), (-1,-1), colors.HexColor('#374151')),
        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
    ]))
    elements.append(t)
    elements.append(Spacer(1, 30))

    # Process messages to find the last assistant response with stages
    last_assistant_msg = None
    for msg in reversed(conversation.get('messages', [])):
        if msg.get('role') == 'assistant' and 'stage3' in msg:
            last_assistant_msg = msg
            break
            
    if not last_assistant_msg:
        elements.append(Paragraph("No completed review found in this conversation.", normal_style))
        doc.build(elements)
        return buffer.getvalue()

    # Stage 3: Final Consensus (First because it's most important)
    elements.append(Paragraph("Final Consensus", heading_style))
    stage3_content = last_assistant_msg.get('stage3', {}).get('response', 'No consensus available.')
    # Handle markdown-ish text simply by replacing newlines
    for line in stage3_content.split('\n'):
        if line.strip():
            elements.append(Paragraph(line, normal_style))
    
    elements.append(Spacer(1, 20))
    elements.append(HRFlowable(width="100%", thickness=1, dashed=True, color=colors.HexColor('#9ca3af')))
    
    # Stage 1: Individual Perspectives
    elements.append(Paragraph("Council Perspectives", heading_style))
    
    for response in last_assistant_msg.get('stage1', []):
        role_name = response.get('model', 'Unknown Role').replace('_', ' ').title()
        content = response.get('response', '')
        
        elements.append(Paragraph(role_name, subheading_style))
        for line in content.split('\n'):
            if line.strip():
                # Basic cleanup of markdown bolding
                clean_line = line.replace('**', '')
                elements.append(Paragraph(clean_line, normal_style))
        
        elements.append(Spacer(1, 10))

    # Footer
    elements.append(Spacer(1, 30))
    elements.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#e5e7eb')))
    elements.append(Paragraph("Generated by Nursing Council Agent from Ai Education", ParagraphStyle(
        'Footer',
        parent=normal_style,
        fontSize=8,
        textColor=colors.gray,
        alignment=1 # Center
    )))

    doc.build(elements)
    buffer.seek(0)
    return buffer.getvalue()
